[workspace]
resolver = "3"
members = [
  "livtet-core",
  "livtet-cli",
  "livtet-cli-common",
  "livtet-temporal-quotes",
  "livtet-data",
  "livtet-search",
  "livtet-types",
  "livtet-test-utils",
  "livtet-ruby",
  "livtet-covers",
]
default-members = [
  "livtet-data",
  "livtet-types",
  "livtet-core",
  "livtet-search",
]

[workspace.package]
edition = "2024"
rust-version = "1.97.0"

[workspace.dependencies]
# Self exports
livtet-core = { path = "livtet-core" }
livtet-cli-common = { path = "livtet-cli-common" }
livtet-data = { path = "livtet-data" }
livtet-search = { path = "livtet-search" }
livtet-test-utils = { path = "livtet-test-utils" }
livtet-types = { path = "livtet-types" }
magnus = "0.8"
uniffi = "0.32"

# Filesystem + I/O
camino = { version = "1", features = ["serde1"] }
camino-tempfile = "1"
fs-err = { version = "3", features = ["tokio"] }
dirs = "7"

# Extensions
fake = { version = "5.1", features = ["ulid", "time", "url", "derive"] }
miette = "7"
mutants = "0"
paste = "1"
rand = "0.10"
rand_core = "0.10"
specta = { version = "2.0.0-rc.25", features = ["camino", "serde_json"] }
strum = { version = "0.28", features = ["derive"] }
thiserror = "2"
time = { version = "0.3", features = ["serde"] }
ulid = { version = "3", features = ["serde", "std"] }

# Async
tokio = { version = "1", features = ["rt", "macros"] }
async-trait = "0.1"
futures-util = "0.3"

# Encoding
hex = "0.4"
jsonschema = { version = "0.56" }
schemars = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = { version = "1.1" }
blurhash = "0.2.3"
image = "0.25.10"

# HTTP
livtet-covers = { path = "livtet-covers" }
reqwest = { version = "0.13", default-features = false }

# o11y
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
mem_forget = "deny"
