[package]
name = "livtet-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[features]
default = ["covers"]
fake = ["dep:fake", "livtet-data/fake", "livtet-types/fake"]
covers = ["dep:livtet-covers"]

[dependencies]
async-trait.workspace = true
camino = { workspace = true }
camino-tempfile = { workspace = true }
dirs = { workspace = true }
fake = { workspace = true, optional = true }
fs-err = { workspace = true }
livtet-data = { workspace = true }
livtet-covers = { workspace = true, optional = true }
livtet-search = { workspace = true }
livtet-types = { workspace = true }
miette = { workspace = true }
mutants = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
strsim = "0.11"
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
