[package]
name = "livtet-ruby"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
livtet-core = { path = "../livtet-core", default-features = false }
livtet-data = { path = "../livtet-data" }
magnus = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
