use std::path::Path;

fn main() {
    // --- Signer public key ---
    println!("cargo:rerun-if-env-changed=LIVTET_BUNDLED_KEY_PATH");
    let key_text = std::env::var("LIVTET_BUNDLED_KEY_PATH")
        .ok()
        .and_then(|p| std::fs::read_to_string(&p).ok())
        .unwrap_or_default();
    println!("cargo:rustc-env=LIVTET_BUNDLED_SIGNER_PUB_TEXT={}", key_text);

    // --- Bundled plugin sources ---
    println!("cargo:rerun-if-env-changed=LIVTET_BUNDLED_PLUGIN_DIR");
    let plugin_dir = std::env::var("LIVTET_BUNDLED_PLUGIN_DIR").unwrap_or_default();
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("bundled_gen.rs");

    if plugin_dir.is_empty() {
        std::fs::write(&dest, "pub fn bundled_index() -> Vec<BundledPluginEntry> {\n    Vec::new()\n}\n")
            .expect("write bundled_gen.rs");
        return;
    }

    let plugin_root = Path::new(&plugin_dir);
    if !plugin_root.is_dir() {
        eprintln!("cargo:warning=LIVTET_BUNDLED_PLUGIN_DIR={plugin_dir:?} is not a directory; no bundled plugins embedded");
        std::fs::write(&dest, "pub fn bundled_index() -> Vec<BundledPluginEntry> {\n    Vec::new()\n}\n")
            .expect("write bundled_gen.rs");
        return;
    }

    // Walk subdirectories, find livtet.toml manifests
    let mut entries = Vec::new();
    if let Ok(read_dir) = std::fs::read_dir(plugin_root) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let manifest_path = path.join("livtet.toml");
            if !manifest_path.is_file() {
                continue;
            }
            // Read the manifest to find entry point and plugin id
            let manifest_toml = match std::fs::read_to_string(&manifest_path) {
                Ok(t) => t,
                Err(e) => {
                    eprintln!("cargo:warning=failed to read {manifest_path:?}: {e}");
                    continue;
                }
            };
            // Quick parse to find id and entry point
            let id = extract_toml_value(&manifest_toml, "id");
            if id.is_empty() {
                eprintln!("cargo:warning={manifest_path:?} has no [plugin] id; skipping");
                continue;
            }
            let entry_file = extract_toml_value(&manifest_toml, "entry");
            let entry = if entry_file.is_empty() {
                "init.lua".to_string()
            } else {
                entry_file
            };
            let entry_path = path.join(&entry);
            if !entry_path.is_file() {
                eprintln!("cargo:warning=entry {entry_path:?} not found for plugin {id}; skipping");
                continue;
            }

            // Compute paths relative to workspace root for include_bytes!/include_str!
            // The build script runs from the crate directory, so paths must be
            // relative to the crate root.
            let manifest_rel = manifest_path.to_string_lossy().replace('\\', "/");
            let entry_rel = entry_path.to_string_lossy().replace('\\', "/");

            // Tell cargo to recompile if these files change
            println!("cargo:rerun-if-changed={manifest_rel}");
            println!("cargo:rerun-if-changed={entry_rel}");

            entries.push(BundledEntry {
                id,
                manifest_path: manifest_rel.to_string(),
                entry_path: entry_rel.to_string(),
            });
        }
    }

    // Generate the bundled_gen.rs file
    let mut code = String::from(
        "// AUTO-GENERATED by build.rs — do not edit.\n\
         #![allow(clippy::all)]\n\
         pub fn bundled_index() -> Vec<BundledPluginEntry> {\n",
    );
    if entries.is_empty() {
        code.push_str("    Vec::new()\n");
    } else {
        code.push_str("    vec![\n");
        for e in &entries {
            let manifest_expr = format!("include_str!({:?})", e.manifest_path);
            let entry_expr = format!("include_bytes!({:?})", e.entry_path);
            code.push_str(&format!(
                "        BundledPluginEntry {{\n\
                 \x20           id: {:?}.to_string(),\n\
                 \x20           manifest: crate::manifest::PluginManifest::from_toml({manifest_expr})\n\
                 \x20               .expect(\"bundled plugin {:?} manifest must be valid\"),\n\
                 \x20           source_bytes: {entry_expr},\n\
                 \x20       }},\n",
                e.id, e.id,
            ));
        }
        code.push_str("    ]\n");
    }
    code.push_str("}\n");
    std::fs::write(&dest, code).expect("write bundled_gen.rs");
}

struct BundledEntry {
    id: String,
    manifest_path: String,
    entry_path: String,
}

/// Quick-and-dirty TOML string extractor for the [plugin] table.
/// Not a full parser — just finds `key = "value"` lines under [plugin].
fn extract_toml_value(toml: &str, key: &str) -> String {
    let mut in_plugin_section = false;
    for line in toml.lines() {
        let trimmed = line.trim();
        if trimmed == "[plugin]" {
            in_plugin_section = true;
            continue;
        }
        if !in_plugin_section {
            continue;
        }
        if trimmed.starts_with('[') {
            // New section — we've left [plugin]
            break;
        }
        if let Some(val) = trimmed.strip_prefix(&format!("{key} = ")) {
            let val = val.trim();
            if val.starts_with('"') && val.ends_with('"') {
                return val[1..val.len() - 1].to_string();
            }
            if val.starts_with('\'') && val.ends_with('\'') {
                return val[1..val.len() - 1].to_string();
            }
            return val.to_string();
        }
    }
    String::new()
}
