[package]
name = "livtet-ffi"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[package.metadata.workspaces]
independent = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
uniffi = { version = "0.32", features = ["tokio"] }
livtet-core.workspace = true
livtet-data = { workspace = true, features = ["fake"] }
livtet-search = { workspace = true, features = ["uniffi"] }
livtet-temporal-quotes.workspace = true
livtet-types = { workspace = true, features = ["uniffi"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
camino.workspace = true
thiserror.workspace = true
time.workspace = true

[features]
cli = ["uniffi/cli"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["cli"]

[dev-dependencies]
livtet-data = { workspace = true, features = ["fake"] }
livtet-test-utils = { workspace = true }
camino-tempfile.workspace = true
fs-err = { workspace = true }
